### PR TITLE
Test fixes

### PR DESCRIPTION
**Pull request by szymonm**

### CODE REVIEW

**Comment by gvolpe** [comment]
Thanks! Waiting for CI to pass, then I'll merge it straight away :)

**Comment by gvolpe** [comment]
Apparently Codeship does not support PR builds from other users :| https://community.codeship.com/t/does-codeship-integrates-with-github-statuses-api/741/16

**Comment by gvolpe** [comment]
Note: This didn't fix the random failure. Still experimenting the issue both locally and in the CI.

**Comment by szymonm** [comment]
:(

**Comment by gvolpe** [comment]
It's not an easy problem to fix anyway, I might need to get rid of the Embedded Qpid Broker and find a better way to unit test. Thanks again for your contributions!

**Pull request merged**
